This program run on
asttokens 3.0.0
attrs 25.1.0
certifi 2025.1.31
cffi 1.17.1
colorama 0.4.6
exceptiongroup 1.2.2
executing 2.2.0
h11 0.14.0
icecream 2.1.4
idna 3.10
outcome 1.3.0.post0
pycparser 2.22
Pygments 2.19.1
PySocks 1.7.1
selenium 4.28.1
setuptools 75.8.0
sniffio 1.3.1
sortedcontainers 2.4.0
trio 0.28.0
trio-websocket 0.11.1
typing_extensions 4.12.2
urllib3 2.3.0
websocket-client 1.8.0
wsproto 1.2.0
python 3.12.8
chromedriver 132.0.6834.159
pip 25.0

Exception and solution
No Python at '"C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe' error
find the python.exe - for me it is C:\Users\user\AppData\Local\Programs\Python\Python310
replaced the link on pyvenv.cfg

make changes

Germany Candidate stage from New Application to CTS across pipeline
New Application > Telephone Interview > Software Engineer > CTS
 
